return {
  "EdenEast/nightfox.nvim",
  lazy = false,
  opts = {
    options = {
      compile_path = vim.fn.stdpath("cache") .. "/nightfox",
      transparent = vim.g.transparent_enabled,
      dim_active = false,
      styles = {
        comments = "italic",
        keywords = "italic",
        functions = "bold",
        loops = "bold",
        booleans = "italic,bold",
      },
      modules = {
        "alpha",
        "cmp",
        "dashboard",
        "dap_ui",
        "diagnostic",
        "fidget",
        "gitsigns",
        "illuminate",
        "indent_blankline",
        "lazy",
        "lsp_semantic_tokens",
        "lsp_trouble",
        "mini",
        "native_lsp",
        "navic",
        "neogit",
        "neotest",
        "neotree",
        "notify",
        "nvimtree",
        "telescope",
        "treesitter",
        "whichkey",
      },
    },
  },
}
