return {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  lsp = {
    highlights = {
      File = "Directory",
      Snippet = "Label",
      Text = "@string",
      Method = "@method",
      Function = "@function",
      Constructor = "@constructor",
      Field = "@field",
      Variable = "@variable",
      Module = "@namespace",
      Property = "@property",
      Unit = "@constant",
      Value = "@variable",
      Enum = "@type",
      Keyword = "@keyword",
      Reference = "@parameter.reference",
      Constant = "@constant",
      Struct = "@structure",
      Event = "@variable",
      Operator = "@operator",
      Namespace = "@namespace",
      Package = "@include",
      String = "@string",
      Number = "@number",
      Boolean = "@boolean",
      Array = "@repeat",
      Object = "@type",
      Key = "@field",
      Null = "@symbol",
      EnumMember = "@field",
      Class = "@lsp.type.class",
      Interface = "@lsp.type.interface",
      TypeParameter = "@lsp.type.parameter",
    },
  }
}
