return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  opts = {
    term_colors = true,
    integrations = {
      alpha = true,
      cmp = true,
      dap = true,
      dap_ui = true,
      dashboard = true,
      diffview = true,
      dropbar = true,
      flash = true,
      gitsigns = true,
      harpoon = true,
      leap = true,
      markdown = true,
      mason = true,
      mini = { enabled = true },
      neotree = true,
      neogit = true,
      noice = true,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = { "undercurl" },
          hints = { "undercurl" },
          warnings = { "undercurl" },
          information = { "undercurl" },
          ok = { "undercurl" },
        },
      },
      navic = true,
      notify = true,
      semantic_tokens = true,
      nvimtree = true,
      treesitter_context = true,
      treesitter = true,
      window_picker = true,
      octo = true,
      rainbow_delimiters = true,
      telescope = { enabled = true },
      lsp_trouble = true,
      illuminate = { enabled = true, lsp = true },
      which_key = true,
    },
  },
}
