local border = require("util.icons").border.rounded
local divider = require("util.icons").dividers.ThinLineMiddle
local group = require("util.icons").ui.CircleSmallEmpty

return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    cmd = "WhichKey",
    opts = {
      plugins = {
        marks = true,
        registers = true,
        spelling = { enabled = true, suggestions = 15 },
      },
      icons = {
        group = group .. " ",
        separator = divider .. " ",
      },
      layout = {
        align = "center",
        height = { min = 3, max = 25 },
        width = { min = 25, max = 50 },
        spacing = 5,
      },
      window = {
        border = border,
        position = "bottom",
        margin = { 0, 1, 0, 1 },
        padding = { 2, 1, 2, 1 },
        winblend = 0,
        zindex = 1000,
      },
      key_labels = {
        ["<space>"] = "[SPACE]",
        ["<CR>"] = "[RETURN]",
        ["<tab>"] = "[TAB]",
        ["<Tab>"] = "[TAB]",
        ["<S-Tab>"] = "[SHIFT] + [TAB]",
        ["<leader>"] = "[LEADER]",
        ["<localleader>"] = "[LOCAL LEADER]",
        ["<Left>"] = " ",
        ["<Right>"] = " ",
        ["<Up>"] = "",
        ["<Down>"] = "",
        ["<C-Left>"] = "[CTRL] +  ",
        ["<C-Right>"] = "[CTRL] +  ",
        ["<C-Up>"] = "[CTRL] + ",
        ["<C-Down>"] = "[CTRL] + ",
        ["<C-/>"] = "[CTRL] + [/]",
        ["<C-Bslash>"] = "[CTRL] + [\\]",
        ["<C-Space>"] = "[CTRL] + [SPACE]",
        ["<c-w>"] = "[CTRL] + w",
        ["<C-B>"] = "[CTRL] + b",
        ["<C-A>"] = "[CTRL] + s",
        ["<C-C>"] = "[CTRL] + c",
        ["<C-S>"] = "[CTRL] + a",
        ["<C-D>"] = "[CTRL] + d",
        ["<C-F>"] = "[CTRL] + f",
        ["<C-H>"] = "[CTRL] + h",
        ["<C-J>"] = "[CTRL] + j",
        ["<C-K>"] = "[CTRL] + k",
        ["<C-L>"] = "[CTRL] + l",
      },
      defaults = {
        ["g"] = { name = "★ goto" },
        ["gs"] = { name = "★ surround" },
        ["z"] = { name = "★ fold" },
        ["]"] = { name = "★ next" },
        ["["] = { name = "★ prev" },
        ["<leader>i"] = { name = " Info" },
        ["<leader><tab>"] = { name = "󰓩 Tabs" },
        ["<leader>b"] = { name = "󰖯 Buffer" },
        ["<leader>c"] = { name = " Code" },
        ["<leader>f"] = { name = "󰈔 File/Find" },
        ["<leader>g"] = { name = " Git" },
        ["<leader>gh"] = { name = "[git] hunks", ["_"] = "which_key_ignore" },
        ["<leader>l"] = { name = "󰒲 Lazy" },
        ["<leader>q"] = { name = "󰗼 Quit/Session" },
        ["<leader>s"] = { name = " Search" },
        ["<leader>u"] = { name = " Ui" },
        ["<leader>w"] = { name = "󱂬 Windows" },
        ["<leader>x"] = { name = "󰁨 Diagnostics/Quickfix" },
      },
    },
  },
}
